export const supportedLanguages = [
  "english",
  "korean",
  "chinese",
  "japanese",
  "spanish",
  "french",
  "german",
  "portuguese",
  "turkish",
  "italian",
  "dutch",
  "polish",
  "ukrainian",
  "romanian",
  "czech",
  "greek",
  "swedish",
  "hungarian",
  "danish",
  "indonesian",
  "thai",
  "vietnamese",
  "hindi",
  "arabic",
  "russian",
  "swahili",
  "filipino",
  "hausa",
  "bengali",
  "urdu",
  "amharic",
  "burmese",
  "khmer",
  "nepali",
  "somali",
  "pashto",
  "lingala",
  "mongolian",
  "lao",
  "malagasy",
  "dari",
  "oromo",
  "chichewa",
  "tigrinya",
  "bambara",
  "fula",
  "wolof",
  "sinhala",
  "tamil",
  "kinyarwanda",
  "kirundi",
  "krio",
  "ewe",
  "fon",
  "sango",
  "moore",
  "kanuri",
  "quechua",
  "aymara",
  "guarani",
  "kongo",
  "zarma",
  "tamasheq",
  "songhay",
  "twi",
  "dagbani",
  "luganda",
  "acholi",
  "dinka",
  "nuer",
  "shona",
  "ndebele",
  "tok_pisin",
  "marathi",
  "telugu",
  "gujarati",
  "kannada",
  "malayalam",
  "yoruba",
  "persian",
  "cantonese",
] as const;

const englishRegionFallbackLanguages = new Set([
  "turkish",
  "italian",
  "dutch",
  "polish",
  "ukrainian",
  "romanian",
  "czech",
  "greek",
  "swedish",
  "hungarian",
  "danish",
  "marathi",
  "telugu",
  "gujarati",
  "kannada",
  "malayalam",
  "yoruba",
  "persian",
  "cantonese",
]);

export const getRegionDatasetName = ({
  body,
  language,
  regionLevel,
}: {
  body: string;
  language: string;
  regionLevel: number;
}) => {
  const normalizedBody = body.toLowerCase();
  const normalizedLanguage = language.toLowerCase();
  const languageSuffix =
    normalizedLanguage === "english" ||
    englishRegionFallbackLanguages.has(normalizedLanguage)
      ? ""
      : `-${normalizedLanguage}`;

  return normalizedBody === "earth"
    ? `region-${regionLevel}${languageSuffix}`
    : `region-${regionLevel}-${normalizedBody}${languageSuffix}`;
};
