import { Locale } from "@/i18n";
import enPlaceTypes from "@/messages/en/placeTypes.json";
import koPlaceTypes from "@/messages/ko/placeTypes.json";
import cnPlaceTypes from "@/messages/cn/placeTypes.json";
import jaPlaceTypes from "@/messages/ja/placeTypes.json";
import esPlaceTypes from "@/messages/es/placeTypes.json";
import frPlaceTypes from "@/messages/fr/placeTypes.json";
import dePlaceTypes from "@/messages/de/placeTypes.json";
import ptPlaceTypes from "@/messages/pt/placeTypes.json";
import trPlaceTypes from "@/messages/tr/placeTypes.json";
import itPlaceTypes from "@/messages/it/placeTypes.json";
import nlPlaceTypes from "@/messages/nl/placeTypes.json";
import plPlaceTypes from "@/messages/pl/placeTypes.json";
import ukPlaceTypes from "@/messages/uk/placeTypes.json";
import roPlaceTypes from "@/messages/ro/placeTypes.json";
import csPlaceTypes from "@/messages/cs/placeTypes.json";
import elPlaceTypes from "@/messages/el/placeTypes.json";
import svPlaceTypes from "@/messages/sv/placeTypes.json";
import huPlaceTypes from "@/messages/hu/placeTypes.json";
import daPlaceTypes from "@/messages/da/placeTypes.json";
import idPlaceTypes from "@/messages/id/placeTypes.json";
import thPlaceTypes from "@/messages/th/placeTypes.json";
import viPlaceTypes from "@/messages/vi/placeTypes.json";
import hiPlaceTypes from "@/messages/hi/placeTypes.json";
import arPlaceTypes from "@/messages/ar/placeTypes.json";
import ruPlaceTypes from "@/messages/ru/placeTypes.json";
import swPlaceTypes from "@/messages/sw/placeTypes.json";
import filPlaceTypes from "@/messages/fil/placeTypes.json";
import haPlaceTypes from "@/messages/ha/placeTypes.json";
import bnPlaceTypes from "@/messages/bn/placeTypes.json";
import urPlaceTypes from "@/messages/ur/placeTypes.json";
import amPlaceTypes from "@/messages/am/placeTypes.json";
import myPlaceTypes from "@/messages/my/placeTypes.json";
import kmPlaceTypes from "@/messages/km/placeTypes.json";
import nePlaceTypes from "@/messages/ne/placeTypes.json";
import soPlaceTypes from "@/messages/so/placeTypes.json";
import psPlaceTypes from "@/messages/ps/placeTypes.json";
import lnPlaceTypes from "@/messages/ln/placeTypes.json";
import mnPlaceTypes from "@/messages/mn/placeTypes.json";
import loPlaceTypes from "@/messages/lo/placeTypes.json";
import mgPlaceTypes from "@/messages/mg/placeTypes.json";
import prsPlaceTypes from "@/messages/prs/placeTypes.json";
import omPlaceTypes from "@/messages/om/placeTypes.json";
import nyPlaceTypes from "@/messages/ny/placeTypes.json";
import tiPlaceTypes from "@/messages/ti/placeTypes.json";
import bmPlaceTypes from "@/messages/bm/placeTypes.json";
import ffPlaceTypes from "@/messages/ff/placeTypes.json";
import woPlaceTypes from "@/messages/wo/placeTypes.json";
import siPlaceTypes from "@/messages/si/placeTypes.json";
import taPlaceTypes from "@/messages/ta/placeTypes.json";
import rwPlaceTypes from "@/messages/rw/placeTypes.json";
import rnPlaceTypes from "@/messages/rn/placeTypes.json";
import kriPlaceTypes from "@/messages/kri/placeTypes.json";
import eePlaceTypes from "@/messages/ee/placeTypes.json";
import fonPlaceTypes from "@/messages/fon/placeTypes.json";
import sgPlaceTypes from "@/messages/sg/placeTypes.json";
import mosPlaceTypes from "@/messages/mos/placeTypes.json";
import krPlaceTypes from "@/messages/kr/placeTypes.json";
import quPlaceTypes from "@/messages/qu/placeTypes.json";
import ayPlaceTypes from "@/messages/ay/placeTypes.json";
import gnPlaceTypes from "@/messages/gn/placeTypes.json";
import kgPlaceTypes from "@/messages/kg/placeTypes.json";
import djePlaceTypes from "@/messages/dje/placeTypes.json";
import tmhPlaceTypes from "@/messages/tmh/placeTypes.json";
import sonPlaceTypes from "@/messages/son/placeTypes.json";
import twPlaceTypes from "@/messages/tw/placeTypes.json";
import dagPlaceTypes from "@/messages/dag/placeTypes.json";
import lgPlaceTypes from "@/messages/lg/placeTypes.json";
import achPlaceTypes from "@/messages/ach/placeTypes.json";
import dinPlaceTypes from "@/messages/din/placeTypes.json";
import nusPlaceTypes from "@/messages/nus/placeTypes.json";
import snPlaceTypes from "@/messages/sn/placeTypes.json";
import ndePlaceTypes from "@/messages/nde/placeTypes.json";
import tpiPlaceTypes from "@/messages/tpi/placeTypes.json";
import mrPlaceTypes from "@/messages/mr/placeTypes.json";
import tePlaceTypes from "@/messages/te/placeTypes.json";
import guPlaceTypes from "@/messages/gu/placeTypes.json";
import knPlaceTypes from "@/messages/kn/placeTypes.json";
import mlPlaceTypes from "@/messages/ml/placeTypes.json";
import yoPlaceTypes from "@/messages/yo/placeTypes.json";
import faPlaceTypes from "@/messages/fa/placeTypes.json";
import yuePlaceTypes from "@/messages/yue/placeTypes.json";
import aaPlaceTypes from "@/messages/aa/placeTypes.json";
import abPlaceTypes from "@/messages/ab/placeTypes.json";
import afPlaceTypes from "@/messages/af/placeTypes.json";
import akPlaceTypes from "@/messages/ak/placeTypes.json";
import sqPlaceTypes from "@/messages/sq/placeTypes.json";
import anPlaceTypes from "@/messages/an/placeTypes.json";
import hyPlaceTypes from "@/messages/hy/placeTypes.json";
import asPlaceTypes from "@/messages/as/placeTypes.json";
import avPlaceTypes from "@/messages/av/placeTypes.json";
import aePlaceTypes from "@/messages/ae/placeTypes.json";
import azPlaceTypes from "@/messages/az/placeTypes.json";
import baPlaceTypes from "@/messages/ba/placeTypes.json";
import euPlaceTypes from "@/messages/eu/placeTypes.json";
import bePlaceTypes from "@/messages/be/placeTypes.json";
import biPlaceTypes from "@/messages/bi/placeTypes.json";
import bsPlaceTypes from "@/messages/bs/placeTypes.json";
import brPlaceTypes from "@/messages/br/placeTypes.json";
import bgPlaceTypes from "@/messages/bg/placeTypes.json";
import caPlaceTypes from "@/messages/ca/placeTypes.json";
import chPlaceTypes from "@/messages/ch/placeTypes.json";
import cePlaceTypes from "@/messages/ce/placeTypes.json";
import cuPlaceTypes from "@/messages/cu/placeTypes.json";
import cvPlaceTypes from "@/messages/cv/placeTypes.json";
import kwPlaceTypes from "@/messages/kw/placeTypes.json";
import coPlaceTypes from "@/messages/co/placeTypes.json";
import crPlaceTypes from "@/messages/cr/placeTypes.json";
import dvPlaceTypes from "@/messages/dv/placeTypes.json";
import dzPlaceTypes from "@/messages/dz/placeTypes.json";
import eoPlaceTypes from "@/messages/eo/placeTypes.json";
import etPlaceTypes from "@/messages/et/placeTypes.json";
import foPlaceTypes from "@/messages/fo/placeTypes.json";
import fjPlaceTypes from "@/messages/fj/placeTypes.json";
import fiPlaceTypes from "@/messages/fi/placeTypes.json";
import fyPlaceTypes from "@/messages/fy/placeTypes.json";
import kaPlaceTypes from "@/messages/ka/placeTypes.json";
import gdPlaceTypes from "@/messages/gd/placeTypes.json";
import gaPlaceTypes from "@/messages/ga/placeTypes.json";
import glPlaceTypes from "@/messages/gl/placeTypes.json";
import gvPlaceTypes from "@/messages/gv/placeTypes.json";
import htPlaceTypes from "@/messages/ht/placeTypes.json";
import hePlaceTypes from "@/messages/he/placeTypes.json";
import hzPlaceTypes from "@/messages/hz/placeTypes.json";
import hoPlaceTypes from "@/messages/ho/placeTypes.json";
import hrPlaceTypes from "@/messages/hr/placeTypes.json";
import igPlaceTypes from "@/messages/ig/placeTypes.json";
import isPlaceTypes from "@/messages/is/placeTypes.json";
import ioPlaceTypes from "@/messages/io/placeTypes.json";
import iiPlaceTypes from "@/messages/ii/placeTypes.json";
import iuPlaceTypes from "@/messages/iu/placeTypes.json";
import iePlaceTypes from "@/messages/ie/placeTypes.json";
import iaPlaceTypes from "@/messages/ia/placeTypes.json";
import ikPlaceTypes from "@/messages/ik/placeTypes.json";
import jvPlaceTypes from "@/messages/jv/placeTypes.json";
import klPlaceTypes from "@/messages/kl/placeTypes.json";
import ksPlaceTypes from "@/messages/ks/placeTypes.json";
import kkPlaceTypes from "@/messages/kk/placeTypes.json";
import kiPlaceTypes from "@/messages/ki/placeTypes.json";
import kyPlaceTypes from "@/messages/ky/placeTypes.json";
import kvPlaceTypes from "@/messages/kv/placeTypes.json";
import kjPlaceTypes from "@/messages/kj/placeTypes.json";
import kuPlaceTypes from "@/messages/ku/placeTypes.json";
import laPlaceTypes from "@/messages/la/placeTypes.json";
import lvPlaceTypes from "@/messages/lv/placeTypes.json";
import liPlaceTypes from "@/messages/li/placeTypes.json";
import ltPlaceTypes from "@/messages/lt/placeTypes.json";
import lbPlaceTypes from "@/messages/lb/placeTypes.json";
import luPlaceTypes from "@/messages/lu/placeTypes.json";
import mkPlaceTypes from "@/messages/mk/placeTypes.json";
import mhPlaceTypes from "@/messages/mh/placeTypes.json";
import miPlaceTypes from "@/messages/mi/placeTypes.json";
import msPlaceTypes from "@/messages/ms/placeTypes.json";
import mtPlaceTypes from "@/messages/mt/placeTypes.json";
import naPlaceTypes from "@/messages/na/placeTypes.json";
import nvPlaceTypes from "@/messages/nv/placeTypes.json";
import nrPlaceTypes from "@/messages/nr/placeTypes.json";
import ngPlaceTypes from "@/messages/ng/placeTypes.json";
import nnPlaceTypes from "@/messages/nn/placeTypes.json";
import nbPlaceTypes from "@/messages/nb/placeTypes.json";
import noPlaceTypes from "@/messages/no/placeTypes.json";
import ocPlaceTypes from "@/messages/oc/placeTypes.json";
import ojPlaceTypes from "@/messages/oj/placeTypes.json";
import orPlaceTypes from "@/messages/or/placeTypes.json";
import osPlaceTypes from "@/messages/os/placeTypes.json";
import paPlaceTypes from "@/messages/pa/placeTypes.json";
import piPlaceTypes from "@/messages/pi/placeTypes.json";
import rmPlaceTypes from "@/messages/rm/placeTypes.json";
import saPlaceTypes from "@/messages/sa/placeTypes.json";
import skPlaceTypes from "@/messages/sk/placeTypes.json";
import slPlaceTypes from "@/messages/sl/placeTypes.json";
import sePlaceTypes from "@/messages/se/placeTypes.json";
import smPlaceTypes from "@/messages/sm/placeTypes.json";
import sdPlaceTypes from "@/messages/sd/placeTypes.json";
import stPlaceTypes from "@/messages/st/placeTypes.json";
import scPlaceTypes from "@/messages/sc/placeTypes.json";
import srPlaceTypes from "@/messages/sr/placeTypes.json";
import ssPlaceTypes from "@/messages/ss/placeTypes.json";
import suPlaceTypes from "@/messages/su/placeTypes.json";
import tyPlaceTypes from "@/messages/ty/placeTypes.json";
import ttPlaceTypes from "@/messages/tt/placeTypes.json";

export interface PlaceDetailsProps {
  map: google.maps.Map | null;
  visible: boolean;
  placeId: string | null;
  location: google.maps.LatLng | null;
  onClose: () => void;
}

export type PlaceTypesRecord = Record<string, string>;

export const placeTypes: Record<Locale, PlaceTypesRecord> = {
  en: enPlaceTypes as PlaceTypesRecord,
  ko: koPlaceTypes as PlaceTypesRecord,
  cn: cnPlaceTypes as PlaceTypesRecord,
  ja: jaPlaceTypes as PlaceTypesRecord,
  es: esPlaceTypes as PlaceTypesRecord,
  fr: frPlaceTypes as PlaceTypesRecord,
  de: dePlaceTypes as PlaceTypesRecord,
  pt: ptPlaceTypes as PlaceTypesRecord,
  tr: trPlaceTypes as PlaceTypesRecord,
  it: itPlaceTypes as PlaceTypesRecord,
  nl: nlPlaceTypes as PlaceTypesRecord,
  pl: plPlaceTypes as PlaceTypesRecord,
  uk: ukPlaceTypes as PlaceTypesRecord,
  ro: roPlaceTypes as PlaceTypesRecord,
  cs: csPlaceTypes as PlaceTypesRecord,
  el: elPlaceTypes as PlaceTypesRecord,
  sv: svPlaceTypes as PlaceTypesRecord,
  hu: huPlaceTypes as PlaceTypesRecord,
  da: daPlaceTypes as PlaceTypesRecord,
  id: idPlaceTypes as PlaceTypesRecord,
  th: thPlaceTypes as PlaceTypesRecord,
  vi: viPlaceTypes as PlaceTypesRecord,
  hi: hiPlaceTypes as PlaceTypesRecord,
  ar: arPlaceTypes as PlaceTypesRecord,
  ru: ruPlaceTypes as PlaceTypesRecord,
  sw: swPlaceTypes as PlaceTypesRecord,
  fil: filPlaceTypes as PlaceTypesRecord,
  ha: haPlaceTypes as PlaceTypesRecord,
  bn: bnPlaceTypes as PlaceTypesRecord,
  ur: urPlaceTypes as PlaceTypesRecord,
  am: amPlaceTypes as PlaceTypesRecord,
  my: myPlaceTypes as PlaceTypesRecord,
  km: kmPlaceTypes as PlaceTypesRecord,
  ne: nePlaceTypes as PlaceTypesRecord,
  so: soPlaceTypes as PlaceTypesRecord,
  ps: psPlaceTypes as PlaceTypesRecord,
  ln: lnPlaceTypes as PlaceTypesRecord,
  mn: mnPlaceTypes as PlaceTypesRecord,
  lo: loPlaceTypes as PlaceTypesRecord,
  mg: mgPlaceTypes as PlaceTypesRecord,
  prs: prsPlaceTypes as PlaceTypesRecord,
  om: omPlaceTypes as PlaceTypesRecord,
  ny: nyPlaceTypes as PlaceTypesRecord,
  ti: tiPlaceTypes as PlaceTypesRecord,
  bm: bmPlaceTypes as PlaceTypesRecord,
  ff: ffPlaceTypes as PlaceTypesRecord,
  wo: woPlaceTypes as PlaceTypesRecord,
  si: siPlaceTypes as PlaceTypesRecord,
  ta: taPlaceTypes as PlaceTypesRecord,
  rw: rwPlaceTypes as PlaceTypesRecord,
  rn: rnPlaceTypes as PlaceTypesRecord,
  kri: kriPlaceTypes as PlaceTypesRecord,
  ee: eePlaceTypes as PlaceTypesRecord,
  fon: fonPlaceTypes as PlaceTypesRecord,
  sg: sgPlaceTypes as PlaceTypesRecord,
  mos: mosPlaceTypes as PlaceTypesRecord,
  kr: krPlaceTypes as PlaceTypesRecord,
  qu: quPlaceTypes as PlaceTypesRecord,
  ay: ayPlaceTypes as PlaceTypesRecord,
  gn: gnPlaceTypes as PlaceTypesRecord,
  kg: kgPlaceTypes as PlaceTypesRecord,
  dje: djePlaceTypes as PlaceTypesRecord,
  tmh: tmhPlaceTypes as PlaceTypesRecord,
  son: sonPlaceTypes as PlaceTypesRecord,
  tw: twPlaceTypes as PlaceTypesRecord,
  dag: dagPlaceTypes as PlaceTypesRecord,
  lg: lgPlaceTypes as PlaceTypesRecord,
  ach: achPlaceTypes as PlaceTypesRecord,
  din: dinPlaceTypes as PlaceTypesRecord,
  nus: nusPlaceTypes as PlaceTypesRecord,
  sn: snPlaceTypes as PlaceTypesRecord,
  nde: ndePlaceTypes as PlaceTypesRecord,
  tpi: tpiPlaceTypes as PlaceTypesRecord,
  mr: mrPlaceTypes as PlaceTypesRecord,
  te: tePlaceTypes as PlaceTypesRecord,
  gu: guPlaceTypes as PlaceTypesRecord,
  kn: knPlaceTypes as PlaceTypesRecord,
  ml: mlPlaceTypes as PlaceTypesRecord,
  yo: yoPlaceTypes as PlaceTypesRecord,
  fa: faPlaceTypes as PlaceTypesRecord,
  yue: yuePlaceTypes as PlaceTypesRecord,
  aa: aaPlaceTypes as PlaceTypesRecord,
  ab: abPlaceTypes as PlaceTypesRecord,
  af: afPlaceTypes as PlaceTypesRecord,
  ak: akPlaceTypes as PlaceTypesRecord,
  sq: sqPlaceTypes as PlaceTypesRecord,
  an: anPlaceTypes as PlaceTypesRecord,
  hy: hyPlaceTypes as PlaceTypesRecord,
  as: asPlaceTypes as PlaceTypesRecord,
  av: avPlaceTypes as PlaceTypesRecord,
  ae: aePlaceTypes as PlaceTypesRecord,
  az: azPlaceTypes as PlaceTypesRecord,
  ba: baPlaceTypes as PlaceTypesRecord,
  eu: euPlaceTypes as PlaceTypesRecord,
  be: bePlaceTypes as PlaceTypesRecord,
  bi: biPlaceTypes as PlaceTypesRecord,
  bs: bsPlaceTypes as PlaceTypesRecord,
  br: brPlaceTypes as PlaceTypesRecord,
  bg: bgPlaceTypes as PlaceTypesRecord,
  ca: caPlaceTypes as PlaceTypesRecord,
  ch: chPlaceTypes as PlaceTypesRecord,
  ce: cePlaceTypes as PlaceTypesRecord,
  cu: cuPlaceTypes as PlaceTypesRecord,
  cv: cvPlaceTypes as PlaceTypesRecord,
  kw: kwPlaceTypes as PlaceTypesRecord,
  co: coPlaceTypes as PlaceTypesRecord,
  cr: crPlaceTypes as PlaceTypesRecord,
  dv: dvPlaceTypes as PlaceTypesRecord,
  dz: dzPlaceTypes as PlaceTypesRecord,
  eo: eoPlaceTypes as PlaceTypesRecord,
  et: etPlaceTypes as PlaceTypesRecord,
  fo: foPlaceTypes as PlaceTypesRecord,
  fj: fjPlaceTypes as PlaceTypesRecord,
  fi: fiPlaceTypes as PlaceTypesRecord,
  fy: fyPlaceTypes as PlaceTypesRecord,
  ka: kaPlaceTypes as PlaceTypesRecord,
  gd: gdPlaceTypes as PlaceTypesRecord,
  ga: gaPlaceTypes as PlaceTypesRecord,
  gl: glPlaceTypes as PlaceTypesRecord,
  gv: gvPlaceTypes as PlaceTypesRecord,
  ht: htPlaceTypes as PlaceTypesRecord,
  he: hePlaceTypes as PlaceTypesRecord,
  hz: hzPlaceTypes as PlaceTypesRecord,
  ho: hoPlaceTypes as PlaceTypesRecord,
  hr: hrPlaceTypes as PlaceTypesRecord,
  ig: igPlaceTypes as PlaceTypesRecord,
  is: isPlaceTypes as PlaceTypesRecord,
  io: ioPlaceTypes as PlaceTypesRecord,
  ii: iiPlaceTypes as PlaceTypesRecord,
  iu: iuPlaceTypes as PlaceTypesRecord,
  ie: iePlaceTypes as PlaceTypesRecord,
  ia: iaPlaceTypes as PlaceTypesRecord,
  ik: ikPlaceTypes as PlaceTypesRecord,
  jv: jvPlaceTypes as PlaceTypesRecord,
  kl: klPlaceTypes as PlaceTypesRecord,
  ks: ksPlaceTypes as PlaceTypesRecord,
  kk: kkPlaceTypes as PlaceTypesRecord,
  ki: kiPlaceTypes as PlaceTypesRecord,
  ky: kyPlaceTypes as PlaceTypesRecord,
  kv: kvPlaceTypes as PlaceTypesRecord,
  kj: kjPlaceTypes as PlaceTypesRecord,
  ku: kuPlaceTypes as PlaceTypesRecord,
  la: laPlaceTypes as PlaceTypesRecord,
  lv: lvPlaceTypes as PlaceTypesRecord,
  li: liPlaceTypes as PlaceTypesRecord,
  lt: ltPlaceTypes as PlaceTypesRecord,
  lb: lbPlaceTypes as PlaceTypesRecord,
  lu: luPlaceTypes as PlaceTypesRecord,
  mk: mkPlaceTypes as PlaceTypesRecord,
  mh: mhPlaceTypes as PlaceTypesRecord,
  mi: miPlaceTypes as PlaceTypesRecord,
  ms: msPlaceTypes as PlaceTypesRecord,
  mt: mtPlaceTypes as PlaceTypesRecord,
  na: naPlaceTypes as PlaceTypesRecord,
  nv: nvPlaceTypes as PlaceTypesRecord,
  nr: nrPlaceTypes as PlaceTypesRecord,
  ng: ngPlaceTypes as PlaceTypesRecord,
  nn: nnPlaceTypes as PlaceTypesRecord,
  nb: nbPlaceTypes as PlaceTypesRecord,
  no: noPlaceTypes as PlaceTypesRecord,
  oc: ocPlaceTypes as PlaceTypesRecord,
  oj: ojPlaceTypes as PlaceTypesRecord,
  or: orPlaceTypes as PlaceTypesRecord,
  os: osPlaceTypes as PlaceTypesRecord,
  pa: paPlaceTypes as PlaceTypesRecord,
  pi: piPlaceTypes as PlaceTypesRecord,
  rm: rmPlaceTypes as PlaceTypesRecord,
  sa: saPlaceTypes as PlaceTypesRecord,
  sk: skPlaceTypes as PlaceTypesRecord,
  sl: slPlaceTypes as PlaceTypesRecord,
  se: sePlaceTypes as PlaceTypesRecord,
  sm: smPlaceTypes as PlaceTypesRecord,
  sd: sdPlaceTypes as PlaceTypesRecord,
  st: stPlaceTypes as PlaceTypesRecord,
  sc: scPlaceTypes as PlaceTypesRecord,
  sr: srPlaceTypes as PlaceTypesRecord,
  ss: ssPlaceTypes as PlaceTypesRecord,
  su: suPlaceTypes as PlaceTypesRecord,
  ty: tyPlaceTypes as PlaceTypesRecord,
  tt: ttPlaceTypes as PlaceTypesRecord,
};
