import { Locale } from "@/i18n";
import enPlaceTypes from "@/messages/en/placeTypes.json";
import koPlaceTypes from "@/messages/ko/placeTypes.json";
import cnPlaceTypes from "@/messages/cn/placeTypes.json";
import jaPlaceTypes from "@/messages/ja/placeTypes.json";
import esPlaceTypes from "@/messages/es/placeTypes.json";
import frPlaceTypes from "@/messages/fr/placeTypes.json";
import dePlaceTypes from "@/messages/de/placeTypes.json";
import ptPlaceTypes from "@/messages/pt/placeTypes.json";
import trPlaceTypes from "@/messages/tr/placeTypes.json";
import itPlaceTypes from "@/messages/it/placeTypes.json";
import nlPlaceTypes from "@/messages/nl/placeTypes.json";
import plPlaceTypes from "@/messages/pl/placeTypes.json";
import ukPlaceTypes from "@/messages/uk/placeTypes.json";
import idPlaceTypes from "@/messages/id/placeTypes.json";
import thPlaceTypes from "@/messages/th/placeTypes.json";
import viPlaceTypes from "@/messages/vi/placeTypes.json";
import hiPlaceTypes from "@/messages/hi/placeTypes.json";
import arPlaceTypes from "@/messages/ar/placeTypes.json";
import ruPlaceTypes from "@/messages/ru/placeTypes.json";
import swPlaceTypes from "@/messages/sw/placeTypes.json";
import filPlaceTypes from "@/messages/fil/placeTypes.json";
import haPlaceTypes from "@/messages/ha/placeTypes.json";
import bnPlaceTypes from "@/messages/bn/placeTypes.json";
import urPlaceTypes from "@/messages/ur/placeTypes.json";
import amPlaceTypes from "@/messages/am/placeTypes.json";
import myPlaceTypes from "@/messages/my/placeTypes.json";
import kmPlaceTypes from "@/messages/km/placeTypes.json";
import nePlaceTypes from "@/messages/ne/placeTypes.json";
import soPlaceTypes from "@/messages/so/placeTypes.json";
import psPlaceTypes from "@/messages/ps/placeTypes.json";
import lnPlaceTypes from "@/messages/ln/placeTypes.json";
import mnPlaceTypes from "@/messages/mn/placeTypes.json";
import loPlaceTypes from "@/messages/lo/placeTypes.json";
import mgPlaceTypes from "@/messages/mg/placeTypes.json";
import prsPlaceTypes from "@/messages/prs/placeTypes.json";
import omPlaceTypes from "@/messages/om/placeTypes.json";
import nyPlaceTypes from "@/messages/ny/placeTypes.json";
import tiPlaceTypes from "@/messages/ti/placeTypes.json";
import bmPlaceTypes from "@/messages/bm/placeTypes.json";
import ffPlaceTypes from "@/messages/ff/placeTypes.json";
import woPlaceTypes from "@/messages/wo/placeTypes.json";
import siPlaceTypes from "@/messages/si/placeTypes.json";
import taPlaceTypes from "@/messages/ta/placeTypes.json";
import rwPlaceTypes from "@/messages/rw/placeTypes.json";
import rnPlaceTypes from "@/messages/rn/placeTypes.json";
import kriPlaceTypes from "@/messages/kri/placeTypes.json";
import eePlaceTypes from "@/messages/ee/placeTypes.json";
import fonPlaceTypes from "@/messages/fon/placeTypes.json";
import sgPlaceTypes from "@/messages/sg/placeTypes.json";
import mosPlaceTypes from "@/messages/mos/placeTypes.json";
import krPlaceTypes from "@/messages/kr/placeTypes.json";
import quPlaceTypes from "@/messages/qu/placeTypes.json";
import ayPlaceTypes from "@/messages/ay/placeTypes.json";
import gnPlaceTypes from "@/messages/gn/placeTypes.json";
import kgPlaceTypes from "@/messages/kg/placeTypes.json";
import djePlaceTypes from "@/messages/dje/placeTypes.json";
import tmhPlaceTypes from "@/messages/tmh/placeTypes.json";
import sonPlaceTypes from "@/messages/son/placeTypes.json";
import twPlaceTypes from "@/messages/tw/placeTypes.json";
import dagPlaceTypes from "@/messages/dag/placeTypes.json";
import lgPlaceTypes from "@/messages/lg/placeTypes.json";
import achPlaceTypes from "@/messages/ach/placeTypes.json";
import dinPlaceTypes from "@/messages/din/placeTypes.json";
import nusPlaceTypes from "@/messages/nus/placeTypes.json";
import snPlaceTypes from "@/messages/sn/placeTypes.json";
import ndePlaceTypes from "@/messages/nde/placeTypes.json";
import tpiPlaceTypes from "@/messages/tpi/placeTypes.json";

export interface PlaceDetailsProps {
  map: google.maps.Map | null;
  visible: boolean;
  placeId: string | null;
  location: google.maps.LatLng | null;
  onClose: () => void;
}

export type PlaceTypesRecord = Record<string, string>;

export const placeTypes: Record<Locale, PlaceTypesRecord> = {
  en: enPlaceTypes as PlaceTypesRecord,
  ko: koPlaceTypes as PlaceTypesRecord,
  cn: cnPlaceTypes as PlaceTypesRecord,
  ja: jaPlaceTypes as PlaceTypesRecord,
  es: esPlaceTypes as PlaceTypesRecord,
  fr: frPlaceTypes as PlaceTypesRecord,
  de: dePlaceTypes as PlaceTypesRecord,
  pt: ptPlaceTypes as PlaceTypesRecord,
  tr: trPlaceTypes as PlaceTypesRecord,
  it: itPlaceTypes as PlaceTypesRecord,
  nl: nlPlaceTypes as PlaceTypesRecord,
  pl: plPlaceTypes as PlaceTypesRecord,
  uk: ukPlaceTypes as PlaceTypesRecord,
  id: idPlaceTypes as PlaceTypesRecord,
  th: thPlaceTypes as PlaceTypesRecord,
  vi: viPlaceTypes as PlaceTypesRecord,
  hi: hiPlaceTypes as PlaceTypesRecord,
  ar: arPlaceTypes as PlaceTypesRecord,
  ru: ruPlaceTypes as PlaceTypesRecord,
  sw: swPlaceTypes as PlaceTypesRecord,
  fil: filPlaceTypes as PlaceTypesRecord,
  ha: haPlaceTypes as PlaceTypesRecord,
  bn: bnPlaceTypes as PlaceTypesRecord,
  ur: urPlaceTypes as PlaceTypesRecord,
  am: amPlaceTypes as PlaceTypesRecord,
  my: myPlaceTypes as PlaceTypesRecord,
  km: kmPlaceTypes as PlaceTypesRecord,
  ne: nePlaceTypes as PlaceTypesRecord,
  so: soPlaceTypes as PlaceTypesRecord,
  ps: psPlaceTypes as PlaceTypesRecord,
  ln: lnPlaceTypes as PlaceTypesRecord,
  mn: mnPlaceTypes as PlaceTypesRecord,
  lo: loPlaceTypes as PlaceTypesRecord,
  mg: mgPlaceTypes as PlaceTypesRecord,
  prs: prsPlaceTypes as PlaceTypesRecord,
  om: omPlaceTypes as PlaceTypesRecord,
  ny: nyPlaceTypes as PlaceTypesRecord,
  ti: tiPlaceTypes as PlaceTypesRecord,
  bm: bmPlaceTypes as PlaceTypesRecord,
  ff: ffPlaceTypes as PlaceTypesRecord,
  wo: woPlaceTypes as PlaceTypesRecord,
  si: siPlaceTypes as PlaceTypesRecord,
  ta: taPlaceTypes as PlaceTypesRecord,
  rw: rwPlaceTypes as PlaceTypesRecord,
  rn: rnPlaceTypes as PlaceTypesRecord,
  kri: kriPlaceTypes as PlaceTypesRecord,
  ee: eePlaceTypes as PlaceTypesRecord,
  fon: fonPlaceTypes as PlaceTypesRecord,
  sg: sgPlaceTypes as PlaceTypesRecord,
  mos: mosPlaceTypes as PlaceTypesRecord,
  kr: krPlaceTypes as PlaceTypesRecord,
  qu: quPlaceTypes as PlaceTypesRecord,
  ay: ayPlaceTypes as PlaceTypesRecord,
  gn: gnPlaceTypes as PlaceTypesRecord,
  kg: kgPlaceTypes as PlaceTypesRecord,
  dje: djePlaceTypes as PlaceTypesRecord,
  tmh: tmhPlaceTypes as PlaceTypesRecord,
  son: sonPlaceTypes as PlaceTypesRecord,
  tw: twPlaceTypes as PlaceTypesRecord,
  dag: dagPlaceTypes as PlaceTypesRecord,
  lg: lgPlaceTypes as PlaceTypesRecord,
  ach: achPlaceTypes as PlaceTypesRecord,
  din: dinPlaceTypes as PlaceTypesRecord,
  nus: nusPlaceTypes as PlaceTypesRecord,
  sn: snPlaceTypes as PlaceTypesRecord,
  nde: ndePlaceTypes as PlaceTypesRecord,
  tpi: tpiPlaceTypes as PlaceTypesRecord,
};
