type Point = [number, number];

export function scanShell(m: number): Point[] {
  const points: Point[] = [];
  const r = Math.floor(Math.sqrt(m));
  for (let x = -r; x <= r; x++) {
    const ySquared = m - x * x;
    const y = Math.floor(Math.sqrt(ySquared));
    if (y * y !== ySquared) continue;
    if (y > 0) {
      points.push([x, y], [x, -y]);
    } else {
      points.push([x, 0]);
    }
  }
  return points;
}

export function symmetricShell(m: number): Point[] {
  const points: Point[] = [];
  const limit = Math.floor(Math.sqrt(m / 2));
  for (let x = 0; x <= limit; x++) {
    const ySquared = m - x * x;
    const y = Math.floor(Math.sqrt(ySquared));
    if (y < x) continue;
    if (y * y === ySquared) addSymmetricPoints(points, x, y);
  }
  return points;
}

export function factorShell(m: number): Point[] {
  // Practical divisor-based shell generation. It uses the sum-of-two-squares
  // theorem only as a filter; actual coordinates are still generated by a
  // bounded representative scan to avoid Gaussian integer reconstruction cost.
  if (!canBeSumOfTwoSquares(m)) return [];
  return symmetricShell(m);
}

type Factor = {
  prime: number;
  exponent: number;
};

export function gaussianIntegerShell(m: number): Point[] {
  if (m === 0) return [[0, 0]];

  const factors = factorize(m);
  let scale = 1;
  let reps: Point[] = [[1, 0]];

  for (const { prime, exponent } of factors) {
    if (prime === 2) {
      const factor = gaussianPow([1, 1], exponent);
      reps = reps.map((rep) => gaussianMultiply(rep, factor));
    } else if (prime % 4 === 3) {
      if (exponent % 2 === 1) return [];
      scale *= prime ** (exponent / 2);
    } else {
      const primeRep = findPrimeSumOfSquares(prime);
      const options: Point[] = [];
      for (let k = 0; k <= exponent; k++) {
        options.push(
          gaussianMultiply(
            gaussianPow(primeRep, k),
            gaussianPow([primeRep[0], -primeRep[1]], exponent - k),
          ),
        );
      }

      const nextReps: Point[] = [];
      for (const rep of reps) {
        for (const option of options) {
          nextReps.push(gaussianMultiply(rep, option));
        }
      }
      reps = nextReps;
    }
  }

  const points: Point[] = [];
  const seenRepresentatives = new Set<string>();

  for (const [real, imaginary] of reps) {
    const x = Math.abs(real * scale);
    const y = Math.abs(imaginary * scale);
    const a = Math.min(x, y);
    const b = Math.max(x, y);
    const key = `${a},${b}`;
    if (seenRepresentatives.has(key)) continue;
    seenRepresentatives.add(key);
    addSymmetricPoints(points, a, b);
  }

  return points;
}

export function gaussianSmallGateShell(m: number): Point[] {
  return m <= 100_000_000 ? gaussianIntegerShell(m) : symmetricShell(m);
}

export function factorize(m: number): Factor[] {
  let n = m;
  const factors: Factor[] = [];

  for (let p = 2; p * p <= n; p += p === 2 ? 1 : 2) {
    if (n % p !== 0) continue;
    let exponent = 0;
    while (n % p === 0) {
      n /= p;
      exponent++;
    }
    factors.push({ prime: p, exponent });
  }

  if (n > 1) factors.push({ prime: n, exponent: 1 });
  return factors;
}

export function findPrimeSumOfSquares(prime: number): Point {
  const limit = Math.floor(Math.sqrt(prime));
  for (let x = 1; x <= limit; x++) {
    const ySquared = prime - x * x;
    const y = Math.floor(Math.sqrt(ySquared));
    if (y * y === ySquared) return [x, y];
  }

  throw new Error(`No sum-of-squares representation for prime ${prime}`);
}

export function gaussianPow(base: Point, exponent: number): Point {
  let result: Point = [1, 0];
  let power = base;
  let n = exponent;

  while (n > 0) {
    if (n & 1) result = gaussianMultiply(result, power);
    power = gaussianMultiply(power, power);
    n = Math.floor(n / 2);
  }

  return result;
}

export function gaussianMultiply(a: Point, b: Point): Point {
  return [a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0]];
}

export function canBeSumOfTwoSquares(m: number): boolean {
  let n = m;
  for (let p = 2; p * p <= n; p++) {
    if (n % p !== 0) continue;
    let exponent = 0;
    while (n % p === 0) {
      n /= p;
      exponent++;
    }
    if (p % 4 === 3 && exponent % 2 === 1) return false;
  }
  return n % 4 !== 3;
}

export function addSymmetricPoints(points: Point[], x: number, y: number) {
  const seen = new Set<string>();
  const candidates: Point[] = [
    [x, y],
    [x, -y],
    [-x, y],
    [-x, -y],
    [y, x],
    [y, -x],
    [-y, x],
    [-y, -x],
  ];

  for (const point of candidates) {
    const key = `${point[0]},${point[1]}`;
    if (seen.has(key)) continue;
    seen.add(key);
    points.push(point);
  }
}

export function sortedKeys(points: Point[]) {
  return points.map(([x, y]) => `${x},${y}`).sort();
}
