import { Locale } from "@/i18n";

export const LOCALE_LABELS: Record<Locale, string> = {
  en: "English",
  ko: "한국어",
  cn: "中文",
  ja: "日本語",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  pt: "Português",
  id: "Bahasa Indonesia",
  th: "ไทย",
  vi: "Tiếng Việt",
  hi: "हिन्दी",
  ar: "العربية",
  ru: "Русский",
  sw: "Kiswahili",
  fil: "Filipino",
  ha: "Hausa",
  bn: "বাংলা",
  ur: "اردو",
  am: "አማርኛ",
  my: "မြန်မာ",
  km: "ខ្មែរ",
  ne: "नेपाली",
  so: "Soomaali",
  ps: "پښتو",
  ln: "Lingála",
};

export const LOCALE_SHORT_LABELS: Record<Locale, string> = {
  en: "EN",
  ko: "KO",
  cn: "CN",
  ja: "JA",
  es: "ES",
  fr: "FR",
  de: "DE",
  pt: "PT",
  id: "ID",
  th: "TH",
  vi: "VI",
  hi: "HI",
  ar: "AR",
  ru: "RU",
  sw: "SW",
  fil: "FIL",
  ha: "HA",
  bn: "BN",
  ur: "UR",
  am: "AM",
  my: "MY",
  km: "KM",
  ne: "NE",
  so: "SO",
  ps: "PS",
  ln: "LN",
};
