import assert from "node:assert/strict";
import { describe, test } from "node:test";

import japaneseWords from "@repo/codebook/codebook-dist/japanese.json";

import { decode, encode } from "../src/index.js";
import { decodeByWordSet, encodeByWordSet } from "../src/wordset.js";

describe("Japanese word set", () => {
  test("keeps the Japanese codebook unique, kana-visible, and natural-word shaped", () => {
    const blockedWords = new Set([
      "あだると",
      "えろ",
      "かじの",
      "きちがい",
      "くそ",
      "せっくす",
      "ぜんら",
      "ちんこ",
      "ぱちんこ",
      "ふうぞく",
      "ぼっき",
      "まんこ",
      "やくざ",
      "しねる",
      "だつごく",
      "はもの",
      "ひばく",
      "いやらしい",
      "うつ",
      "うつびょう",
      "うんこう",
      "おっぱい",
      "おしっこ",
      "おうけ",
      "きたがわ",
      "きちく",
      "きょうあく",
      "きょうとう",
      "げろ",
      "けが",
      "けんじゅう",
      "げんばく",
      "こうたいし",
      "さつい",
      "さつがい",
      "ざこ",
      "じさつ",
      "しこしこ",
      "しにがみ",
      "しな",
      "しんじゅう",
      "しんた",
      "しんばし",
      "すけべ",
      "せいえき",
      "せいへき",
      "せいよく",
      "だいきらい",
      "たいま",
      "だんあつ",
      "だんやく",
      "ちつ",
      "ちんぴら",
      "ちんぽ",
      "でぶ",
      "とばく",
      "どくさい",
      "はくがい",
      "はだか",
      "はつじょう",
      "ぱちすろ",
      "ぱんちら",
      "ばくにゅう",
      "ひがしぐち",
      "ひとごろし",
      "ひわい",
      "ふじ",
      "ぶす",
      "へんたい",
      "ぼうりょく",
      "まっさつ",
      "まるだし",
      "みずほ",
      "むらむら",
      "やくざい",
      "やけど",
      "ゆううつ",
      "りゃくだつ",
      "ため",
      "もの",
      "した",
      "とも",
      "たい",
      "こう",
      "しょ",
      "ごと",
      "べい",
      "かせい",
      "やよい",
      "ばくふ",
      "きょうとう",
      "たちばな",
      "おびえ",
      "きずつく",
      "げきたい",
      "しがい",
      "じはく",
      "しんれい",
      "つんでれ",
      "にょうぼう",
      "ぼつ",
      "めかくし",
      "よばわり",
      "ろうひ",
      "しょた",
      "じょうみゃく",
      "びく",
      "かざま",
      "きら",
      "きらら",
      "くらしき",
      "こせき",
      "しんすい",
      "たいとう",
      "ちゅうたい",
      "さとおや",
      "ぜんか",
      "たんしょう",
      "ろしゅつ",
      "しけい",
      "しょけい",
      "けいば",
      "きょうてい",
      "ちゅうどく",
      "じゅうしょう",
      "ぎゃくたい",
      "とっこう",
      "へいたい",
      "こうげき",
      "たいほ",
      "てきたい",
      "しょばつ",
      "たいほう",
      "じゅう",
      "どく",
      "やじゅう",
      "ぼうこう",
      "うわき",
      "げり",
      "くず",
      "ぶた",
      "ぶたにく",
      "ふともも",
      "したぎ",
      "しょくよく",
      "のろい",
      "たいくつ",
      "ふこう",
      "ひと",
      "いい",
      "なか",
      "いま",
      "まえ",
      "あと",
      "よい",
      "うえ",
      "ほか",
      "よく",
      "とき",
      "くる",
      "おもい",
      "きょにゅう",
      "しゃせい",
      "せいてき",
      "ちじょ",
      "どれい",
      "さべつ",
      "ぶき",
      "せんとう",
      "ばくはつ",
      "ぐんじ",
      "あんさつ",
      "しゅうげき",
      "ぎゃくさつ",
      "ひっさつ",
      "ぶりょく",
      "らんぼう",
      "げきは",
      "とうばつ",
      "はれつ",
      "げきつい",
      "ぐんそう",
      "はんざい",
      "さぎ",
      "せっとう",
      "だっそう",
      "ぎぞう",
      "とうちょう",
      "かんごく",
      "とつげき",
      "そげき",
      "しゅつげき",
      "せいあつ",
      "けっとう",
      "しぼう",
      "ばばあ",
      "いろけ",
      "ぬぎ",
      "みずぎ",
      "ぼにゅう",
      "れんあい",
      "こいびと",
      "はつこい",
      "だっこ",
      "はいぐう",
      "どうせい",
      "けいさつ",
      "ぼっしゅう",
      "きんし",
      "しはい",
      "ばくろ",
      "やまい",
      "しゅじゅつ",
      "いたみ",
      "びょうとう",
      "きぜつ",
      "しんさつ",
      "ちりょう",
      "かんじゃ",
      "いりょう",
      "きゅうめい",
      "ちび",
      "ださい",
      "ぽんこつ",
      "くさい",
      "しゃちく",
      "けち",
      "しり",
      "くび",
      "じごく",
      "さいあく",
      "つらい",
      "かなしい",
      "きょうふ",
      "おそれ",
      "おそろしい",
      "もんく",
      "せいき",
      "せいし",
      "ちくび",
      "はかい",
      "ぐんたい",
      "ごうとう",
      "ゆうかい",
      "まやく",
      "やくぶつ",
      "せんし",
      "せんじょう",
      "せんじゅつ",
      "せんりょく",
      "せんたい",
      "せんりょう",
      "せんじ",
      "せんき",
      "へいき",
      "へいし",
      "ようへい",
      "はんげき",
      "だげき",
      "しんげき",
      "ちょくげき",
      "いちげき",
      "うばう",
      "おそう",
      "うらぎり",
      "にくしみ",
      "ぎせい",
      "ふせい",
      "せいふく",
      "せいさい",
      "つみ",
      "へい",
      "あくやく",
      "のうやく",
      "ばつ",
      "こわい",
      "こわす",
      "こわれる",
      "うらみ",
      "いかり",
      "あらし",
      "こどく",
      "きのどく",
      "くすり",
      "かんご",
      "いたい",
      "いたずら",
      "せいり",
      "せいべつ",
      "いせい",
      "よくせい",
      "かくせい",
      "まんせい",
      "きゅうせい",
      "はだ",
      "びはだ",
      "みにくい",
      "ごう",
      "やく",
      "ばく",
      "げき",
      "いた",
      "うら",
      "いか",
      "やふおく",
      "らっく",
      "すま",
      "ちょ",
      "りょ",
      "ぐぐ",
      "ぴか",
      "ぶれ",
      "どす",
      "げや",
      "びら",
      "ふせ",
      "つと",
      "かか",
      "うさ",
      "あだ",
      "しい",
      "しこ",
      "ぼし",
      "はなのえ",
      "つぼみえ",
      "さくらば",
      "ばんだい",
      "とほ",
      "でか",
      "じゃ",
      "おつ",
      "けつ",
      "すけ",
      "ばり",
      "ちゃら",
      "やから",
      "もやい",
      "いぐさ",
      "おみなえし",
      "ふじばかま",
      "からたち",
      "しゃくなげ",
      "さるすべり",
      "こなら",
      "みずなら",
      "むくげ",
      "くちなし",
      "ぜんまい",
      "しだ",
      "もみじば",
      "まつば",
      "くさのみ",
      "ほかけぶね",
      "こぶね",
      "えまき",
      "まきもの",
      "つきかげ",
      "ゆうなぎ",
      "あけぼの",
      "そよぎ",
      "かなで",
      "こより",
      "あさひ",
      "すばる",
      "むじるし",
      "じんぐう",
      "おおはし",
      "にしがわ",
      "みなみがわ",
      "やまて",
      "なんかい",
    ]);

    assert.equal(japaneseWords.length, 5000);
    assert.equal(new Set(japaneseWords).size, japaneseWords.length);
    assert.ok(
      japaneseWords.every((word) => /^[\p{Script=Hiragana}]+$/u.test(word)),
    );
    assert.ok(
      japaneseWords.every((word) => word.length >= 2 && word.length <= 7),
    );
    assert.ok(japaneseWords.every((word) => !blockedWords.has(word)));
    assert.ok(japaneseWords.every((word) => !/[っん]$/u.test(word)));

    for (let index = 0; index < japaneseWords.length; index += 20) {
      const block = japaneseWords.slice(index, index + 20);
      const prefixCount = new Map<string, number>();
      for (const word of block) {
        const prefix = [...word].slice(0, 2).join("");
        prefixCount.set(prefix, (prefixCount.get(prefix) ?? 0) + 1);
      }

      assert.ok(Math.max(...prefixCount.values()) < 12);
    }
  });

  test("roundtrips Japanese word-set codes", async () => {
    const encoded = await encodeByWordSet({
      n: 123456789,
      language: "japanese",
    });

    assert.match(encoded, /[\p{Script=Hiragana}\p{Script=Katakana}ー]/u);
    assert.equal(
      await decodeByWordSet({ encoded, language: "japanese" }),
      123456789,
    );
  });

  test("detects Japanese encoded ground codes", async () => {
    const target = { lat: 37.566, lng: 126.978 };
    const encoded = await encode(target, {
      regionLevel: 2,
      language: "japanese",
    });

    assert.match(encoded, /[\p{Script=Hiragana}\p{Script=Katakana}ー]/u);

    const decoded = await decode(encoded);
    assert.ok(Math.abs(decoded.lat - target.lat) < 0.0002);
    assert.ok(Math.abs(decoded.lng - target.lng) < 0.0002);
  });
});
