import assert from "node:assert/strict";
import { describe, test } from "node:test";

import chineseWords from "@repo/codebook/codebook-dist/chinese.json";
import englishWords from "@repo/codebook/codebook-dist/english.json";
import japaneseWords from "@repo/codebook/codebook-dist/japanese.json";
import koreanWords from "@repo/codebook/codebook-dist/korean.json";
import spanishWords from "@repo/codebook/codebook-dist/spanish.json";
import frenchWords from "@repo/codebook/codebook-dist/french.json";
import germanWords from "@repo/codebook/codebook-dist/german.json";
import portugueseWords from "@repo/codebook/codebook-dist/portuguese.json";
import indonesianWords from "@repo/codebook/codebook-dist/indonesian.json";
import thaiWords from "@repo/codebook/codebook-dist/thai.json";
import vietnameseWords from "@repo/codebook/codebook-dist/vietnamese.json";
import hindiWords from "@repo/codebook/codebook-dist/hindi.json";
import arabicWords from "@repo/codebook/codebook-dist/arabic.json";
import russianWords from "@repo/codebook/codebook-dist/russian.json";
import swahiliWords from "@repo/codebook/codebook-dist/swahili.json";
import filipinoWords from "@repo/codebook/codebook-dist/filipino.json";
import hausaWords from "@repo/codebook/codebook-dist/hausa.json";
import bengaliWords from "@repo/codebook/codebook-dist/bengali.json";
import urduWords from "@repo/codebook/codebook-dist/urdu.json";
import amharicWords from "@repo/codebook/codebook-dist/amharic.json";
import burmeseWords from "@repo/codebook/codebook-dist/burmese.json";
import khmerWords from "@repo/codebook/codebook-dist/khmer.json";
import nepaliWords from "@repo/codebook/codebook-dist/nepali.json";
import somaliWords from "@repo/codebook/codebook-dist/somali.json";
import pashtoWords from "@repo/codebook/codebook-dist/pashto.json";
import lingalaWords from "@repo/codebook/codebook-dist/lingala.json";

const assertBlockedWordsAbsent = (words: string[], blockedWords: string[]) => {
  const blocked = new Set(blockedWords);
  assert.deepEqual(
    words.filter((word) => blocked.has(word)),
    [],
  );
};

const assertWordsPresent = (words: string[], expectedWords: string[]) => {
  const available = new Set(words);
  assert.deepEqual(
    expectedWords.filter((word) => !available.has(word)),
    [],
  );
};

const germanTemplateCompoundPattern =
  /^[A-Z][a-z]{3,}(?:band|bank|becher|beet|beutel|blatt|blech|brett|bund|dose|eimer|faden|fass|feld|fliese|gabel|glas|griff|haken|hut|kachel|kanne|karton|kasten|kelle|kerze|kiste|klotz|knopf|korb|kranz|kreide|krug|lampe|leiste|mappe|matte|messer|nadel|papier|perle|pfanne|pfeife|pinsel|platte|polster|rahmen|riegel|ring|rohr|sack|schale|seil|sieb|sohle|spange|spatel|spiegel|spule|steg|stein|stift|tafel|tasche|tasse|tisch|topf|truhe|vlies|wagen)$/u;
const portugueseTemplateCompoundPattern =
  /^[A-Z][a-z]{3,}(?:anel|banco|bandeja|bastao|bau|bolsa|botao|brocha|caixa|cesta|cesto|chave|copo|corda|cuba|cuia|escova|esteira|fita|folha|frasco|gancho|jarra|lata|livro|lona|luz|mapa|marco|mesa|pano|pote|prato|rede|saco|selo|suporte|tabua|tampa|tela|tigela|vaso|vela)$/u;
const assertScriptCodebook = ({
  words,
  pattern,
  expectedWords,
  blockedWords,
}: {
  words: string[];
  pattern: RegExp;
  expectedWords: string[];
  blockedWords: string[];
}) => {
  assert.equal(words.length, 5000);
  assert.equal(new Set(words).size, words.length);
  assert.deepEqual(
    words.filter((word) => !pattern.test(word)),
    [],
  );
  assertWordsPresent(words, expectedWords);
  assertBlockedWordsAbsent(words, blockedWords);
};

const assertCodebook = ({
  words,
  expectedLength,
  blockedWords,
}: {
  words: string[];
  expectedLength: number;
  blockedWords: string[];
}) => {
  assert.equal(words.length, expectedLength);
  assert.equal(new Set(words).size, words.length);

  assertBlockedWordsAbsent(words, blockedWords);
};

describe("reviewed multilingual codebooks", () => {
  test("keeps reviewed English codebook terms out", () => {
    assertCodebook({
      words: englishWords,
      expectedLength: 6000,
      blockedWords: [
        "Squirting",
        "Vibrators",
        "Cialis",
        "Travesti",
        "Facial",
        "Thongs",
        "Interracial",
        "Lesbians",
        "Lingerie",
        "Bikini",
        "Booty",
        "Babes",
        "Gambling",
        "Roulette",
        "Blackjack",
        "Poker",
        "Betting",
        "Bet",
        "Lottery",
        "Holdem",
        "Shooting",
        "Execution",
        "Army",
        "Battle",
        "Combat",
        "Military",
        "Soldier",
        "Soldiers",
        "Troops",
        "Blade",
        "Sword",
        "Threat",
        "Destroy",
        "Destroyed",
        "Destruction",
        "Fighting",
        "Tramadol",
        "Discrimination",
        "Corruption",
        "Adults",
        "Dating",
        "Lovers",
        "Romantic",
        "Pleasure",
        "Personals",
        "Beer",
        "Wine",
        "Drinking",
        "Illness",
        "Diseases",
        "Disorders",
        "Diabetes",
        "Infection",
        "Injection",
        "Injuries",
        "Surgery",
        "Surgical",
        "Patient",
        "Patients",
        "Hospital",
        "Hospitals",
        "Clinic",
        "Depression",
        "Anxiety",
        "Disability",
        "Disabilities",
        "Politics",
        "Political",
        "Religion",
        "Religious",
        "Catholic",
        "Christians",
        "Church",
        "Adam",
        "Alex",
        "Anna",
        "Brian",
        "David",
        "Jennifer",
        "John",
        "Robert",
        "Smith",
        "Austin",
        "Atlanta",
        "Britain",
        "Detroit",
        "Geneva",
        "Honolulu",
        "Michigan",
        "Philadelphia",
        "Washington",
        "York",
        "Slot",
        "Slots",
        "Dice",
        "Gaming",
        "Racing",
        "Medication",
        "Medicine",
        "Diagnosis",
        "Symptoms",
        "Syndrome",
        "Burn",
        "Burns",
        "President",
        "Democrats",
        "Election",
        "Government",
        "Regime",
        "Protest",
        "Saint",
        "Faith",
        "Holy",
        "Prayer",
        "Christmas",
        "Worst",
        "Gross",
        "Rejected",
        "Desperate",
        "Impossible",
        "Fails",
        "Alan",
        "Alice",
        "Ben",
        "Daniel",
        "Athens",
        "Dakota",
        "Oregon",
        "Prague",
        "Venice",
        "Virginia",
        "Amberly",
        "Arborly",
        "Bloomly",
        "Cedarly",
        "Glenlet",
        "Hayshed",
        "Amberbloom",
        "Dangerous",
        "Accidents",
        "Medications",
        "Medicare",
        "Treatment",
        "Treatments",
        "Healthcare",
        "Physicians",
        "Pharmacy",
        "Diagnostic",
        "Surveillance",
        "Violations",
        "Enforcement",
        "Conservative",
        "Congressional",
        "Presidential",
        "Democracy",
        "Democratic",
        "Senate",
        "Republic",
        "Governor",
        "Ministry",
        "Minister",
        "Elections",
        "Heaven",
        "Pray",
        "Divine",
        "Temple",
        "Chapel",
        "Easter",
        "Halloween",
        "Valentine",
        "Sorry",
        "Weak",
        "Risks",
        "Adverse",
        "Negative",
        "Unfortunately",
        "Fault",
        "Problems",
        "Cloverly",
        "Fernvale",
        "Lakelet",
        "Mossbank",
        "Oakvale",
        "Pinevale",
        "Sunvale",
        "Windvale",
        "Grovelet",
        "Blossomwood",
        "Brightfield",
        "Amberbrook",
        "Amberfield",
        "Ambergarden",
        "Ambergrove",
        "Amberhaven",
        "Amberleaf",
        "Ambermeadow",
        "Amberpath",
        "Amberpond",
        "Amberridge",
        "Amberstone",
        "Ambervale",
        "Amberwood",
        "Amberbranch",
        "Amberbreeze",
        "Ambersprout",
        "Ambertrail",
        "Brightbrook",
        "Brightgarden",
        "Brightgrove",
        "Brighthaven",
        "Brightmeadow",
        "Brightpath",
        "Brightpond",
        "Pinecrest",
        "Cedarcrest",
        "Oakcrest",
        "Elmcrest",
        "Birchcrest",
        "Ferncrest",
        "Greenfield",
        "Stonefield",
        "Brookfield",
        "Meadowbrook",
        "Cloverfield",
        "Willowfield",
        "Maplefield",
        "Gardenpath",
        "Gardenstone",
        "Gardenbench",
        "Riverpath",
        "Shadehouse",
        "Leafmore",
        "Indianapolis",
        "Jacksonville",
        "Pennsylvania",
        "Massachusetts",
        "Minneapolis",
        "Connecticut",
        "Baltimore",
        "Cambridge",
        "Vegas",
        "Wales",
        "Shakespeare",
        "Davis",
        "Ashley",
        "Ryan",
        "Nasa",
        "Unix",
        "Linux",
        "Perl",
        "Wiki",
        "Bio",
        "Dvd",
        "Eur",
        "Faq",
        "Rss",
        "Tel",
        "Blog",
        "Byte",
        "Euro",
        "Expo",
        "Info",
        "Mega",
        "Nano",
        "Stat",
        "Const",
        "Cyber",
        "Debug",
        "Email",
        "Indie",
        "Intro",
        "Modem",
        "Multi",
        "Pixel",
        "Utils",
        "Avatar",
        "Config",
        "Cookie",
        "Debian",
        "Pubmed",
        "Signup",
        "Struct",
        "Techno",
        "Weblog",
        "Bizrate",
        "Expansys",
        "Verizon",
        "Rica",
        "Rico",
        "Herbary",
        "Leafbud",
        "Firthwood",
        "Verzeichnis",
        "Arizona",
        "Zealand",
        "Louisville",
        "Alexander",
        "Elizabeth",
        "Nascar",
        "Eminem",
        "Hilton",
        "Hudson",
        "Marcus",
        "Monroe",
        "Nicole",
        "Norton",
        "Rogers",
        "Spears",
        "Watson",
        "Barnes",
        "Evans",
        "Darwin",
        "Dublin",
        "Latina",
      ],
    });
  });
});
