import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, test } from "node:test";

import {
  MAX_SOURCE_LINES,
  evaluateSourceFile,
  isCheckedSourcePath,
} from "./code-size-policy.mjs";

describe("code size policy", () => {
  test("accepts maintained source at the line limit", () => {
    assert.equal(
      evaluateSourceFile({
        path: "src/ok.ts",
        source: Array(MAX_SOURCE_LINES).fill("line").join("\n"),
      }),
      null,
    );
  });

  test("reports maintained source above the line limit", () => {
    assert.deepEqual(
      evaluateSourceFile({
        path: "src/large.ts",
        source: Array(MAX_SOURCE_LINES + 1)
          .fill("line")
          .join("\n"),
      }),
      { path: "src/large.ts", lines: 451, reason: "maintained source" },
    );
  });

  test("accepts only declared generated output with the matching header", () => {
    const source = [
      "// Generated by scripts/generate-output.mjs.",
      ...Array(MAX_SOURCE_LINES).fill("line"),
    ].join("\n");
    assert.equal(
      evaluateSourceFile({
        path: "src/output.generated.ts",
        source,
        generatedFiles: new Map([
          ["src/output.generated.ts", "scripts/generate-output.mjs"],
        ]),
      }),
      null,
    );
    assert.deepEqual(
      evaluateSourceFile({ path: "src/output.generated.ts", source }),
      {
        path: "src/output.generated.ts",
        lines: 451,
        reason: "maintained source",
      },
    );
  });

  test("checks TypeScript and MJS source but not declarations or data", () => {
    assert.equal(isCheckedSourcePath("src/a.ts"), true);
    assert.equal(isCheckedSourcePath("src/a.tsx"), true);
    assert.equal(isCheckedSourcePath("scripts/a.mjs"), true);
    assert.equal(isCheckedSourcePath("src/a.d.ts"), false);
    assert.equal(isCheckedSourcePath("data/a.json"), false);
  });

  test("keeps app runtime modules within the maintained-source limit", () => {
    const paths = [
      "apps/grok-spiral/lib/grok-spiral.ts",
      "apps/web/components/google-map/earth-3d-map.tsx",
      "apps/web/components/google-map/planetary-3d-map.tsx",
      "apps/api-ground-codes/src/postgis-region-store.ts",
      "packages/ground-codes/src/wordset.ts",
      "packages/ground-codes/src/wordset-language.ts",
      "packages/ground-codes/src/wordset-loader-primary.ts",
      "packages/ground-codes/src/wordset-loader-secondary.ts",
    ];

    assert.deepEqual(
      paths.flatMap((path) => {
        const violation = evaluateSourceFile({
          path,
          source: readFileSync(path, "utf8"),
        });
        return violation ? [violation] : [];
      }),
      [],
    );
  });
});
