import assert from "node:assert/strict";
import { describe, test } from "node:test";

import { MAX_SOURCE_LINES, evaluateSourceFile } from "./code-size-policy.mjs";

describe("code size policy", () => {
  test("accepts maintained source at the line limit", () => {
    assert.equal(
      evaluateSourceFile({
        path: "src/ok.ts",
        source: Array(MAX_SOURCE_LINES).fill("line").join("\n"),
      }),
      null,
    );
  });

  test("reports maintained source above the line limit", () => {
    assert.deepEqual(
      evaluateSourceFile({
        path: "src/large.ts",
        source: Array(MAX_SOURCE_LINES + 1)
          .fill("line")
          .join("\n"),
      }),
      { path: "src/large.ts", lines: 451, reason: "maintained source" },
    );
  });

  test("accepts only declared generated output with the matching header", () => {
    const source = [
      "// Generated by scripts/generate-output.mjs.",
      ...Array(MAX_SOURCE_LINES).fill("line"),
    ].join("\n");
    assert.equal(
      evaluateSourceFile({
        path: "src/output.generated.ts",
        source,
        generatedFiles: new Map([
          ["src/output.generated.ts", "scripts/generate-output.mjs"],
        ]),
      }),
      null,
    );
    assert.deepEqual(
      evaluateSourceFile({ path: "src/output.generated.ts", source }),
      {
        path: "src/output.generated.ts",
        lines: 451,
        reason: "maintained source",
      },
    );
  });
});
